[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[features]
default = []
bootanim = []
cpu_slow = []
forceslowlogging = []
fat_trace = []
usb_trace = []
ps2_trace = []
heap_trace = []
heap_debug = []
kernelmb2 = []
selftest = []
iommu_trace = []
lockdep = []

[dependencies]
spin = "0.9"
log = "0.4"
common = { path = "../common" }
framebuffer = { path = "../graphics/Framebuffer" }
hashbrown = "0.14"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15"
aml = "0.16.4"

