//! Normalized key codes for UInputL.
//!
//! These are *physical* key codes (evdev-style, numbered after the Linux
//! `KEY_*` constants) — they never encode a character or a language.  A
//! PS/2 driver reports that the physical key `KeyA` was pressed; the
//! [`crate::input::keymap::Keymap`] translates `KeyA` + modifier state into a
//! character.  This is what keeps language/layout logic out of the hardware
//! drivers.

/// Physical key code.  The discriminants intentionally match the Linux
/// `KEY_*` input event codes so the numbers are familiar and stable.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum KeyCode {
    Escape = 1,
    Digit1 = 2,
    Digit2 = 3,
    Digit3 = 4,
    Digit4 = 5,
    Digit5 = 6,
    Digit6 = 7,
    Digit7 = 8,
    Digit8 = 9,
    Digit9 = 10,
    Digit0 = 11,
    Minus = 12,
    Equal = 13,
    Backspace = 14,
    Tab = 15,
    Q = 16,
    W = 17,
    E = 18,
    R = 19,
    T = 20,
    Y = 21,
    U = 22,
    I = 23,
    O = 24,
    P = 25,
    LeftBrace = 26,
    RightBrace = 27,
    Enter = 28,
    ControlLeft = 29,
    A = 30,
    S = 31,
    D = 32,
    F = 33,
    G = 34,
    H = 35,
    J = 36,
    K = 37,
    L = 38,
    Semicolon = 39,
    Apostrophe = 40,
    Grave = 41,
    ShiftLeft = 42,
    Backslash = 43,
    Z = 44,
    X = 45,
    C = 46,
    V = 47,
    B = 48,
    N = 49,
    M = 50,
    Comma = 51,
    Dot = 52,
    Slash = 53,
    ShiftRight = 54,
    KeypadMultiply = 55,
    AltLeft = 56,
    Space = 57,
    CapsLock = 58,
    F1 = 59,
    F2 = 60,
    F3 = 61,
    F4 = 62,
    F5 = 63,
    F6 = 64,
    F7 = 65,
    F8 = 66,
    F9 = 67,
    F10 = 68,
    NumLock = 69,
    ScrollLock = 70,
    Keypad7 = 71,
    Keypad8 = 72,
    Keypad9 = 73,
    KeypadSubtract = 74,
    Keypad4 = 75,
    Keypad5 = 76,
    Keypad6 = 77,
    KeypadAdd = 78,
    Keypad1 = 79,
    Keypad2 = 80,
    Keypad3 = 81,
    Keypad0 = 82,
    KeypadDecimal = 83,
    F11 = 87,
    F12 = 88,
    KeypadEnter = 96,
    ControlRight = 97,
    KeypadDivide = 98,
    PrintScreen = 99,
    AltRight = 100,
    Home = 102,
    ArrowUp = 103,
    PageUp = 104,
    ArrowLeft = 105,
    ArrowRight = 106,
    End = 107,
    ArrowDown = 108,
    PageDown = 109,
    Insert = 110,
    Delete = 111,
    Pause = 119,
    SuperLeft = 125,
    SuperRight = 126,
    Menu = 127,
}

impl KeyCode {
    /// Raw numeric code (as carried in [`crate::input::event::InputEvent::code`]).
    pub fn code(self) -> u32 {
        self as u32
    }

    /// Look up a key code from its numeric value.
    pub fn from_code(code: u32) -> Option<KeyCode> {
        // All discriminants are non-zero and contiguous-ish; a straight match
        // is clearer than `mem::transmute` and rejects undefined values.
        match code {
            1 => Some(KeyCode::Escape),
            2 => Some(KeyCode::Digit1),
            3 => Some(KeyCode::Digit2),
            4 => Some(KeyCode::Digit3),
            5 => Some(KeyCode::Digit4),
            6 => Some(KeyCode::Digit5),
            7 => Some(KeyCode::Digit6),
            8 => Some(KeyCode::Digit7),
            9 => Some(KeyCode::Digit8),
            10 => Some(KeyCode::Digit9),
            11 => Some(KeyCode::Digit0),
            12 => Some(KeyCode::Minus),
            13 => Some(KeyCode::Equal),
            14 => Some(KeyCode::Backspace),
            15 => Some(KeyCode::Tab),
            16 => Some(KeyCode::Q),
            17 => Some(KeyCode::W),
            18 => Some(KeyCode::E),
            19 => Some(KeyCode::R),
            20 => Some(KeyCode::T),
            21 => Some(KeyCode::Y),
            22 => Some(KeyCode::U),
            23 => Some(KeyCode::I),
            24 => Some(KeyCode::O),
            25 => Some(KeyCode::P),
            26 => Some(KeyCode::LeftBrace),
            27 => Some(KeyCode::RightBrace),
            28 => Some(KeyCode::Enter),
            29 => Some(KeyCode::ControlLeft),
            30 => Some(KeyCode::A),
            31 => Some(KeyCode::S),
            32 => Some(KeyCode::D),
            33 => Some(KeyCode::F),
            34 => Some(KeyCode::G),
            35 => Some(KeyCode::H),
            36 => Some(KeyCode::J),
            37 => Some(KeyCode::K),
            38 => Some(KeyCode::L),
            39 => Some(KeyCode::Semicolon),
            40 => Some(KeyCode::Apostrophe),
            41 => Some(KeyCode::Grave),
            42 => Some(KeyCode::ShiftLeft),
            43 => Some(KeyCode::Backslash),
            44 => Some(KeyCode::Z),
            45 => Some(KeyCode::X),
            46 => Some(KeyCode::C),
            47 => Some(KeyCode::V),
            48 => Some(KeyCode::B),
            49 => Some(KeyCode::N),
            50 => Some(KeyCode::M),
            51 => Some(KeyCode::Comma),
            52 => Some(KeyCode::Dot),
            53 => Some(KeyCode::Slash),
            54 => Some(KeyCode::ShiftRight),
            55 => Some(KeyCode::KeypadMultiply),
            56 => Some(KeyCode::AltLeft),
            57 => Some(KeyCode::Space),
            58 => Some(KeyCode::CapsLock),
            59 => Some(KeyCode::F1),
            60 => Some(KeyCode::F2),
            61 => Some(KeyCode::F3),
            62 => Some(KeyCode::F4),
            63 => Some(KeyCode::F5),
            64 => Some(KeyCode::F6),
            65 => Some(KeyCode::F7),
            66 => Some(KeyCode::F8),
            67 => Some(KeyCode::F9),
            68 => Some(KeyCode::F10),
            69 => Some(KeyCode::NumLock),
            70 => Some(KeyCode::ScrollLock),
            71 => Some(KeyCode::Keypad7),
            72 => Some(KeyCode::Keypad8),
            73 => Some(KeyCode::Keypad9),
            74 => Some(KeyCode::KeypadSubtract),
            75 => Some(KeyCode::Keypad4),
            76 => Some(KeyCode::Keypad5),
            77 => Some(KeyCode::Keypad6),
            78 => Some(KeyCode::KeypadAdd),
            79 => Some(KeyCode::Keypad1),
            80 => Some(KeyCode::Keypad2),
            81 => Some(KeyCode::Keypad3),
            82 => Some(KeyCode::Keypad0),
            83 => Some(KeyCode::KeypadDecimal),
            87 => Some(KeyCode::F11),
            88 => Some(KeyCode::F12),
            96 => Some(KeyCode::KeypadEnter),
            97 => Some(KeyCode::ControlRight),
            98 => Some(KeyCode::KeypadDivide),
            99 => Some(KeyCode::PrintScreen),
            100 => Some(KeyCode::AltRight),
            102 => Some(KeyCode::Home),
            103 => Some(KeyCode::ArrowUp),
            104 => Some(KeyCode::PageUp),
            105 => Some(KeyCode::ArrowLeft),
            106 => Some(KeyCode::ArrowRight),
            107 => Some(KeyCode::End),
            108 => Some(KeyCode::ArrowDown),
            109 => Some(KeyCode::PageDown),
            110 => Some(KeyCode::Insert),
            111 => Some(KeyCode::Delete),
            119 => Some(KeyCode::Pause),
            125 => Some(KeyCode::SuperLeft),
            126 => Some(KeyCode::SuperRight),
            127 => Some(KeyCode::Menu),
            _ => None,
        }
    }
}
